# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-AutoForm
version:      1.02
version_from: lib/CGI/AutoForm.pm
installdirs:  site
requires:
    DBIx::IO:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
